#!/usr/bin/env python3
"""
Fray CI — GitHub Actions workflow generator for automated WAF testing on PRs

Usage:
    fray ci init                Generate .github/workflows/fray-waf-test.yml
    fray ci init --target URL   Set the default target URL
    fray ci init --categories xss,sqli  Only test specific categories
    fray ci show                Print the workflow YAML to stdout

Generates a GitHub Actions workflow that:
    1. Triggers on pull_request events
    2. Installs Fray from PyPI
    3. Runs WAF detection + payload tests
    4. Posts results as a PR comment
    5. Optionally sends webhook notifications
"""

import os
import sys
from pathlib import Path
from typing import List, Optional

from fray import __version__


class Colors:
    """Terminal colors"""
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    RED = '\033[91m'
    BLUE = '\033[94m'
    BOLD = '\033[1m'
    DIM = '\033[2m'
    END = '\033[0m'


# ── Workflow Templates ───────────────────────────────────────────────────────

def generate_workflow(
    target: Optional[str] = None,
    categories: Optional[List[str]] = None,
    max_payloads: int = 50,
    webhook_url: Optional[str] = None,
    timeout: int = 8,
    delay: float = 0.5,
    fail_on_bypass: bool = False,
    comment_on_pr: bool = True,
) -> str:
    """Generate a GitHub Actions workflow YAML for Fray WAF testing."""

    target_line = f'"{target}"' if target else '"${{{{ secrets.FRAY_TARGET_URL }}}}"'

    category_flag = ""
    if categories:
        category_flag = f"--category {categories[0]}"

    webhook_step = ""
    if webhook_url:
        webhook_step = f'          --webhook "{webhook_url}" \\'
    else:
        webhook_step = '          ${{ secrets.FRAY_WEBHOOK_URL && format(\'--webhook {0}\', secrets.FRAY_WEBHOOK_URL) || \'\' }} \\'

    fail_step = ""
    if fail_on_bypass:
        fail_step = """
      - name: Check bypass threshold
        if: always()
        run: |
          if [ -f fray_results.json ]; then
            PASSED=$(python3 -c "import json; d=json.load(open('fray_results.json')); print(d.get('summary',{}).get('passed',0))")
            if [ "$PASSED" -gt "0" ]; then
              echo "::error::$PASSED payload(s) bypassed the WAF"
              exit 1
            fi
          fi"""

    comment_step = ""
    if comment_on_pr:
        comment_step = """
      - name: Comment on PR
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let summary = 'Fray WAF test results not available.';
            try {
              const data = JSON.parse(fs.readFileSync('fray_results.json', 'utf8'));
              const s = data.summary || {};
              const icon = s.passed > 0 ? ':warning:' : ':white_check_mark:';
              summary = [
                `## ${icon} Fray WAF Test Results`,
                '',
                `| Metric | Value |`,
                `|--------|-------|`,
                `| Target | \`${data.target || 'N/A'}\` |`,
                `| Total Payloads | ${s.total || 0} |`,
                `| Blocked | ${s.blocked || 0} |`,
                `| Bypassed | ${s.passed || 0} |`,
                `| Block Rate | ${s.block_rate || 'N/A'} |`,
                `| Duration | ${data.duration || 'N/A'} |`,
                '',
                `> Powered by [Fray](https://github.com/dalisecurity/fray) v""" + __version__ + """`,
              ].join('\\n');
            } catch (e) {
              summary = ':x: Fray WAF test failed to produce results.';
            }
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: summary
            });"""

    workflow = f"""# Fray WAF Security Test — Auto-generated by fray ci v{__version__}
# Docs: https://github.com/dalisecurity/fray
#
# Secrets required:
#   FRAY_TARGET_URL  — Target URL to test (if not hardcoded below)
#   FRAY_WEBHOOK_URL — (Optional) Slack/Discord/Teams webhook for notifications

name: Fray WAF Test

on:
  pull_request:
    branches: [ main, master, hugo ]
  workflow_dispatch:
    inputs:
      target_url:
        description: 'Target URL to test'
        required: true
        type: string
      category:
        description: 'Payload category (blank for all)'
        required: false
        type: string

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  waf-test:
    name: WAF Security Test
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Fray
        run: pip install fray

      - name: Run environment check
        run: fray doctor

      - name: Detect WAF
        run: |
          TARGET={target_line}
          if [ -n "${{{{ github.event.inputs.target_url }}}}" ]; then
            TARGET="${{{{ github.event.inputs.target_url }}}}"
          fi
          fray detect "$TARGET"

      - name: Run WAF payload tests
        run: |
          TARGET={target_line}
          if [ -n "${{{{ github.event.inputs.target_url }}}}" ]; then
            TARGET="${{{{ github.event.inputs.target_url }}}}"
          fi
          CATEGORY="${{{{ github.event.inputs.category || '{categories[0] if categories else ""}' }}}}"
          fray test "$TARGET" \\
            ${{{{ CATEGORY && format('--category {{0}}', CATEGORY) || '' }}}} \\
            --max {max_payloads} \\
            --timeout {timeout} \\
            --delay {delay} \\
            --output fray_results.json \\
{webhook_step}
            || true

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fray-results
          path: fray_results.json
          retention-days: 30
{fail_step}
{comment_step}
"""
    return workflow


def generate_minimal_workflow(target: Optional[str] = None) -> str:
    """Generate a minimal one-job workflow for quick setup."""
    target_line = f'"{target}"' if target else '"${{ secrets.FRAY_TARGET_URL }}"'
    return f"""# Fray WAF Test (minimal) — fray ci v{__version__}
name: Fray WAF Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  waf-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install fray
      - run: fray detect {target_line}
      - run: fray test {target_line} --max 50 --output fray_results.json || true
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: fray-results
          path: fray_results.json
"""


# ── CI Commands ──────────────────────────────────────────────────────────────

def run_ci(
    action: str = "init",
    target: Optional[str] = None,
    categories: Optional[List[str]] = None,
    max_payloads: int = 50,
    webhook: Optional[str] = None,
    fail_on_bypass: bool = False,
    no_comment: bool = False,
    minimal: bool = False,
    output_dir: Optional[str] = None,
):
    """Entry point for fray ci command."""

    if action == "show":
        if minimal:
            print(generate_minimal_workflow(target))
        else:
            print(generate_workflow(
                target=target,
                categories=categories,
                max_payloads=max_payloads,
                webhook_url=webhook,
                fail_on_bypass=fail_on_bypass,
                comment_on_pr=not no_comment,
            ))
        return

    # action == "init"
    base_dir = Path(output_dir) if output_dir else Path.cwd()
    workflows_dir = base_dir / ".github" / "workflows"
    workflow_file = workflows_dir / "fray-waf-test.yml"

    if workflow_file.exists():
        overwrite = input(
            f"  {Colors.YELLOW}{workflow_file} already exists. Overwrite? [y/N]: {Colors.END}"
        ).strip().lower()
        if overwrite not in ("y", "yes"):
            print(f"  {Colors.DIM}Skipped.{Colors.END}")
            return

    workflows_dir.mkdir(parents=True, exist_ok=True)

    if minimal:
        content = generate_minimal_workflow(target)
    else:
        content = generate_workflow(
            target=target,
            categories=categories,
            max_payloads=max_payloads,
            webhook_url=webhook,
            fail_on_bypass=fail_on_bypass,
            comment_on_pr=not no_comment,
        )

    workflow_file.write_text(content, encoding="utf-8")

    print(f"\n{Colors.BOLD}Fray CI v{__version__}{Colors.END}")
    print(f"{Colors.DIM}{'─' * 50}{Colors.END}")
    print(f"  {Colors.GREEN}Created: {workflow_file}{Colors.END}")
    print()
    print(f"  {Colors.DIM}Next steps:{Colors.END}")
    print(f"  1. Set repository secret: {Colors.BLUE}FRAY_TARGET_URL{Colors.END}")
    if not no_comment:
        print(f"  2. PR comments are enabled (requires {Colors.BLUE}pull-requests: write{Colors.END})")
    print(f"  3. Commit and push .github/workflows/fray-waf-test.yml")
    print(f"  4. Open a PR to trigger the workflow")
    print()
    if webhook:
        print(f"  {Colors.DIM}Webhook: {webhook}{Colors.END}")
    else:
        print(f"  {Colors.DIM}Optional: set {Colors.BLUE}FRAY_WEBHOOK_URL{Colors.END} secret for Slack/Discord/Teams notifications{Colors.END}")
    print()
